const types = {};

// Application Types

types.app = {};
types.content = {};
// App types
types.app.HANDLE_CLICK_MENU = 'HANDLE_CLICK_MENU';
types.app.HANDLE_CLICK_MOBILE_MENU = 'HANDLE_CLICK_MOBILE_MENU';
// Content Types
types.content.HANDLE_LOADING = 'HANDLE_LOADING';
types.content.HANDLE_TOP_LOADING_PROGRESS = 'HANDLE_TOP_LOADING_PROGRESS';

types.content.HANDLE_LOADING_CONTENT = 'HANDLE_LOADING_CONTENT';

types.content.UPDATE_CONTENT_PATH = 'UPDATE_CONTENT_PATH';

types.content.TOPICS_DATA_FETCH_SUCCESS = 'TOPICS_DATA_FETCH_SUCCESS';
types.content.TOPICS_DATA_FETCH_FAILED = 'TOPICS_DATA_FETCH_FAILED';

types.content.CONTENT_DATA_FETCH_SUCCESS = 'CONTENT_DATA_FETCH_SUCCESS';
types.content.CONTNET_DATA_FETCH_FAILED = 'CONTNET_DATA_FETCH_FAILED';
types.content.HANDLE_CLICK_CLEAR_MESSAGE = 'HANDLE_CLICK_CLEAR_MESSAGE';

export default types;
